### ISSUE TITLE
Feature Request: kW when charging

### ISSUE THREAD

**Issue by BadgerLoaf** [gndean/home-assistant-hypervolt-charger#19]
Hey GD

Not sure if the API will allow this, but when charging is there anyway to grab the kW being sent to the car?

Use case is when using excess solar, would be useful to see how much kW is being sent to the car real-time.

Thanks again for all your work on this!

**Comment by exalyte** [comment]
This can sort of be done using

sensor.hypervolt_ct_power

However I think from previous discussions this is just all the power being
drawn not just the car, for me I'm convinced it's just the car after
numerous tests.

Or you can use the amps and run a calculation to get watts which might be
more reliable than the CT sensor


Exa

**Comment by BadgerLoaf** [comment]
Yes I suspect converting the amps might be the way to go.

Was going to probably to create a template sensor to do that. Wanted to check in the meantime if the API gave access already; or whether @gndean would consider doing the amps conversion within the integration to allow easier deployments for those that don't play around in YAML much,

**Comment by gndean** [comment]
Yeah, there's nothing I'm aware of within the API that would give realtime power.

As @exalyte says, CT Power potentially measures more than just the car charging, I guess depending on where the external CT clamp is situated. For me,  it certainly measures more than just the car charging.

I had considered exposing a sensor that just multiplied the charger current x voltage. But it looks like the Hypervolt 3.0 doesn't ever set the voltage within the API: https://github.com/gndean/home-assistant-hypervolt-charger/issues/18 So maybe the best that could be done with be to used some fixed voltage. But then, that feels like something that could be done with HA itself.

**Comment by gndean** [comment]
Reopening this with a potential solution.

Please see and try out:

## 1.2.0 Beta

Added new sensor:
### Hypervolt Session Power
Estimates the current charging power.

This measures increases within the `Hypervolt Session Energy` sensor to estimate the instantaneous power. Since the increments with `Hypervolt Session Energy` are somewhat lumpy, an up-to-a 5 minute window is used to calculate the current power. So if the power changes mid-charge, there will be some lag before it's reflected in this sensor. Similarly, the values within the first minute or so can be noisy. 
But since the sensor uses the same figures as the energy calculation from the charger, they should lead to consistent figures and sum up to total energy consumed.

**Comment by BadgerLoaf** [comment]
Thanks @gndean, I’ll test this out this weekend 👍

**Comment by gndean** [comment]
How are you getting on with this?
I've released it as part of version 1.2.1, as I needed to push out a fix, so I've rolled it into that.

**Comment by gndean** [comment]
Closing now as this has been released

**Comment by gndean** [comment]
The integration now exposes a "EV Power" entity which should be used instead of Session Power. The HV APIs provide this power measurement so it's likely to be more accurate and quicker to respond than the derived Session Power value.
