### ISSUE TITLE
Question about CT monitoring

### ISSUE THREAD

**Issue by edmooredop** [gndean/home-assistant-hypervolt-charger#25]
When our Hypervolt 3.0 was installed the electrician didn't run the CT cable in at all (long story, it would have been a very complicated route). However I do have a third party CT clamp that reports back into Home Assistant.

We're getting a solar + Powerwall system installed in a few weeks, and I'm just wondering if I can essentially replicate the functionality of the Hypervolt "solar" modes using this add-on - presumably I can use the powerwall and existing CT data entities to toggle the Hypervolt to 'charge' within this add-on? Or would I be gaining additional functionality if I bit the bullet and got the electrician back to do a long and fiddly cable run back to the consumer unit from the Hypervolt.

Kind of a shame Hypervolt don't support a wireless CT clamp system like the myenergi harvii...

**Comment by gndean** [comment]
Sorry for the slow reply.

You could definitely replicate some similar functionality. Since you will have a Powerwall, it's not so important to exactly match the charging current to the solar excess since the battery acts as a buffer.

I have a bunch of automations relating the charging the car that, when enabled, keep the home battery level between 90% and 100% state of charge and adjust the HV current and state to keep it within that range. i.e. start charging the car when SoC > 95% and there is solar generation beyond a threshold and the house consumption is below a threshold etc.

![image](https://github.com/gndean/home-assistant-hypervolt-charger/assets/18371246/b92c770d-2f25-4558-b029-d724f041e65c)

**Comment by gndean** [comment]
I've had a look at my automation logic and it's quite specific to my home set up with my particular battery and power monitoring, helpers, immersion switch etc... 

It's not something I'm willing to support I'm afraid. I'd rather focus on the core integration, so I'm going to close this.
