### ISSUE TITLE
Hypervolt Charge Mode changes not applied

### ISSUE THREAD

**Issue by johnbradshw** [gndean/home-assistant-hypervolt-charger#54]
Hypervolt 3.0

Updates to the "Hypervolt Charge Mode" are not applied to the device. There are no errors in the log, HA then shows the wrong charge mode.

Steps:

**Reported status**
HA: Charge mode boost
HV: Charge mode boost

**Make Change**
Apply Super Eco Mode in HA

** New reported status **
HA: Charge mode Super Eco Mode
HV: Charge mode boost

**Comment by gndean** [comment]
What's your Activation Mode when you do this?
If in Schedule, the Charge Mode won't have any effect - because that's set by the schedule sessions.
If in Plug and Charge, is the HV app showing the correct state?
For example, if I set Plug and Charge, and Boost, the wait for the car to start charging, then set Super Eco in HA (and with no solar), the car stops charging but the HV app still shows Boost. Even after refreshing the app or killing it and restarting it. -> The HV app is wrong in this case.
I saw similar issues when testing with the HV app on two devices - they didn't stay in sync.

**Comment by GPDixon** [comment]
I'm seeing similar... linked to the issue I raised a few weeks ago. Occasionally the SUPER ECO settings seems to get changed to BOOST without me doing anything! If you recall this was happening immediately after my HA automation set the mode to SUPER ECO and was overcome by setting it 3 times in succession with a 5 second delay (not elegant but worked). I thought this had 'fixed' the problem but now I've found evidence of SUPER ECO being changed to BOOST in the background when nothing I'm doing is taking place! Happened at 00:28 this morning and my car started to charge at this point! It was already fully charged by the time I really wanted to charge it. It's either (a) something that the hypervolt 3.0 is doing itself or (b) its something in the integration? I'm guessing its (a) but could it be anything to do with losing and then re-establishing connection in the integration? It's dependent on the hypervolt cloud access, not the charger itself, right? Only reason I ask is that my cloud access is rock solid (wired connection from HA) but I've been fiddling with my wifi this week and I know that the charger has dropped out a few times! Seems weird that this is the only attribute that has this problem.
